/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sorter_InsertionSorter */

#ifndef _Included_sorter_InsertionSorter
#define _Included_sorter_InsertionSorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sorter_InsertionSorter
 * Method:    insertionsort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_sorter_InsertionSorter_insertionsort
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
